spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_network_api  # Make sure this is correct and the DB exists
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Set to 'none' to prevent automatic schema generation. You can change it to 'update' for dev
    open-in-view: false  # Set too false to prevent lazy loading issues in views
    show-sql: true  # Show SQL queries in the logs (optional)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQLs dialect for Hibernate
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: user  # You can leave this blank for FakeSMTP or MailHog
    password: password  # Same for this
    properties:
      mail:
        smtp:
          trust: "*"
          auth: false  # MailHog and FakeSMTP typically do not require authentication
          starttls.enable: false  # Disable StartTLS for local SMTP servers like MailHog
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

  sql:
    init:
      mode: always

application:
  security:
    jwt:
      secret-key: mXd104lCUWYoQqR8EU+z2lHHJUso3JRM8zoWcry4BUM=
      expiration-time: 86400000  # 24 hours in milliseconds
server:
  port: 8080


#-Dspring:
#  profiles:
#    active=test: