spring:
  profiles:
    active: test # docker
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false



management:
  endpoints:
    web:
      exposure:
        include: beans,loggers,metrics,health,info,readiness  # Expose specific Spring Boot Actuator endpoints for monitoring