# application-docker.yml
server:
  port: 8088  # Docker-specific port

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/book_network_api
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: mail-dev-bsn
    port: 1025
    username: ali
    password: ali
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 10000  # Increase timeout
        timeout: 10000           # Increase read timeout
        writetimeout: 10000      # Increase write timeout

management:
  endpoints:
    web:
      exposure:
        include: beans,loggers,metrics,health,info,readiness
