# application-docker.yml
server:
  port: 8088  # Docker-specific port

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/book_network_api
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: beans,loggers,metrics,health,info,readiness
